# fly.toml app configuration file generated for afrifanz-waitlist on 2024-02-23T22:16:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'afrifanz-waitlist'
primary_region = 'ams'

[build]

[env]
  EMAIL_SENDER = "Afrifanz <hello@afrifanz.com>"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
